# General section
# site:
#   full_name: SB - Silvestar's personal website
#   short_name: SB
#   description: Silvestar is a fearless web developer eager to prove his worth
#   logo: /gfx/svg/logo.svg
#   language: en

# Menu section
# menu:
#   centered: true
#   display_logo: true
#   items:
#     Home: /
#     Blog: /categories/articles
#     Portfolio: /portfolio
#     About: /about-me

# Homepage section
# home_page:
#   - section:
#     title: Silvestar Bistrović
#     paragraphs:
#      - Fearless web developer
#   - section:
#     title: Specializations
#     paragraphs:
#       - Frontend
#       - User Interface
#       - Wordpress
#       - Web Optimization
#   - section:
#     title: Projects
#     links:
#       Starter Project: //starter.silvestarbistrovic.from.hr
#       Hexo Theme SB: //sbtheme.silvestarbistrovic.from.hr
#       Contiamo: //www.contiamo.com
#       Irina and Matej: //irinaandmatej.com
#   - section:
#     title: Links
#     links:
#       Mail: mailto:me@silvestarbistrovic.from.hr?Subject=Hello
#       Twitter: //twitter.com/malimirkeccita
#       Github: //github.com/maliMirkec

# Open Graph section
# open_graph:
#   pretty_url: true
#   image: /gfx/jpg/sb-big.jpg
#   fb:
#     fb_id: 340933169673372
#     fb_admins: malimirkeccita
#   twitter:
#     twitter_id: malimirkeccita
#   google_plus:
#     google_plus_id: +SilvestarbistrovicFromHr

# Widgets
# widgets:
#   contact:
#     mail: mailto:me@silvestarbistrovic.from.hr?Subject=Hello
#     twitter: //twitter.com/malimirkeccita
#     linkedin: //www.linkedin.com/in/starbist/
#     facebook: //www.facebook.com/silvestarbistrovic.from.hr/
#     medium: //medium.com/@malimirkeccita
#     github: //github.com/maliMirkec
#     codepen: //codepen.io/CiTA/
#     lastfm: //www.last.fm/user/maliMirkec
#   google_analytics:
#     tracking_id: UA-12345678-9
#   disqus:
#     shortname: silvestarbistrovic
#   sharing:
#     twitter: malimirkeccita
#     facebook: silvestarbistrovic.from.hr
