site:
  full_name: SB - Silvestar's personal website
  short_name: SB
  description: Silvestar is a fearless web developer eager to prove his worth
  author: Silvestar Bistrović
  logo: /gfx/svg/logo.svg

open_graph:
  pretty_url: true
  image: /gfx/SB-big.png
  fb:
    fb_id: 340933169673372
    fb_admins: malimirkeccita
  twitter:
    twitter_id: malimirkeccita
  google_plus:
    google_plus_id: +SilvestarbistrovicFromHr

menu:
  Home: /
  Blog: /categories/articles
  Portfolio: /portfolio
  About: /about-me

widgets:
  breadcrumbs: true
  contact:
    mail: mailto:me@silvestarbistrovic.from.hr?Subject=Hello
    twitter: https://twitter.com/malimirkeccita
    linkedin: https://www.linkedin.com/in/starbist/
    facebook: https://www.facebook.com/silvestarbistrovic.from.hr/
    medium: https://medium.com/@malimirkeccita
    github: https://github.com/maliMirkec
    codepen: https://codepen.io/CiTA/
    lastfm: https://www.last.fm/user/maliMirkec
  google_analytics:
    tracking_id: UA-37881833-5
  disqus:
    shortname: silvestarbistrovic
  sharing:
    twitter: malimirkeccita
    facebook: silvestarbistrovic.from.hr
