[[redirects]]
  from = "/"
  to = "https://www.silvestar.codes/side-projects/sbtheme/"
  status = 301
  force = true

[[redirects]]
  from = "/about/"
  to = "https://www.silvestar.codes/side-projects/sbtheme/about/"
  status = 301
  force = true

[[redirects]]
  from = "/categories/docs/"
  to = "https://www.silvestar.codes/side-projects/sbtheme/docs/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/getting-started/"
  to = "https://www.silvestar.codes/side-projects/sbtheme/getting-started/"
  status = 301
  force = true

[[redirects]]
  from = "/tags/hexo/"
  to = "https://www.silvestar.codes/side-projects/sbtheme/tags-hexo/"
  status = 301
  force = true

[[redirects]]
  from = "/tags/theme/"
  to = "https://www.silvestar.codes/side-projects/sbtheme/tags-hexo/"
  status = 301
  force = true
